spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/igreja?createDatabaseIfNotExist=true
    username: root
    password: biodev6279**

  jpa:
    show-sql: true
